// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnionIssue.Linq2DB.Persistence;

#nullable disable

namespace UnionIssue.Linq2DB.Migrations.MSSQL
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241003100433_initialSeed")]
    partial class initialSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UnionIssue.Linq2DB.Persistence.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7deeb025-f735-42d7-ae92-920a6b66d18c"),
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("50e486be-fb72-4f4c-beef-ee64f5ad7b22"),
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("UnionIssue.Linq2DB.Persistence.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c077db1-69b6-464d-b1c4-0c4a8e8d69da"),
                            CustomerId = new Guid("7deeb025-f735-42d7-ae92-920a6b66d18c"),
                            ProductName = "Laptop",
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("01bbf701-588e-4c73-ac01-366b5b74df66"),
                            CustomerId = new Guid("50e486be-fb72-4f4c-beef-ee64f5ad7b22"),
                            ProductName = "Smartphone",
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("UnionIssue.Linq2DB.Persistence.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("18548d7d-21b2-4f7d-a403-0fbfe43f4876"),
                            Name = "Laptop",
                            Price = 1200.00m
                        },
                        new
                        {
                            Id = new Guid("fc717d64-f928-4b90-a213-6cdfb9362230"),
                            Name = "Smartphone",
                            Price = 800.00m
                        });
                });

            modelBuilder.Entity("UnionIssue.Linq2DB.Persistence.Order", b =>
                {
                    b.HasOne("UnionIssue.Linq2DB.Persistence.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("UnionIssue.Linq2DB.Persistence.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
